# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasicExample
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxDataSources'#, '3.1.0'

  target 'BasicExampleTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RxBlocking', '6.1.0'
    pod 'RxTest', '6.1.0'
  end


end
