# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Github

  pod 'RxSwift', '4.4.0'
  pod 'RxCocoa', '4.4.0'
  pod 'RxDataSources', '3.1.0'
  pod 'Moya/RxSwift', '12.0.1'
  pod 'SnapKit', '4.2.0'

  target 'GithubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
