# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchExample

  pod 'Moya', '12.0.1'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

end
