# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleProject

  pod 'Moya', '12.0.1'
  pod 'SnapKit', '4.2.0'

end
